import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SpeedInsights } from "@vercel/speed-insights/next";
import Header from "./_components/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by MJ's passion",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={
          inter.className +
          " w-full h-fit min-h-screen flex justify-center bg-slate-200 text-slate-600"
        }
      >
        <Header />
        <main className="w-full max-w-[1000px] h-fit pt-28 flex flex-col items-center ">
          {children}
        </main>
        <SpeedInsights />
      </body>
    </html>
  );
}
